### ISSUE TITLE
Can you share the codes of ESGN?

### ISSUE THREAD

**Issue by PKULiuHui** [ttengwang/dense-video-captioning-pytorch#1]
I have meet a problem when I implement the ESGN in 'Streamlined dense video captioning', can you share your codes of ESGN?

**Comment by ttengwang** [comment]
I will add the code of ESGN a few days later.

**Comment by PKULiuHui** [comment]
Hey, thanks for your attention. Actually I solved my problem, but I'm glad to see your version.
However, there is another problem. I tested RL model on the 1000 small val dataset. I get the results: 

For ground-truths proposals, METEOR 14.51, CIDEr 25.20, Bleu_4 1.46
For leant proposals, METEOR 10.14, CIDEr 9.25, Bleu_4 0.72
Although METEOR looks well, CIDEr and Bleu is poor, especially for learnt proposals. Is this because SCST use METEOR as the reward? What's your results?

**Comment by ttengwang** [comment]
@PKULiuHui Yes, using METEOR as reward would lead to the decreasing of other metrics. I think using METEOR +CIDEr can partly relieve this problem, bu it can not reach the best METEOR.

**Comment by ttengwang** [comment]
> I have meet a problem when I implement the ESGN in 'Streamlined dense video captioning', can you share your codes of ESGN?

Hi, my reimplementation of ESGN is at [here](https://github.com/ttengwang/ESGN). Suggestions are welcome.

**Comment by PKULiuHui** [comment]
Thanks. I will have a look.
