### ISSUE TITLE
how to caption other videos?

### ISSUE THREAD

**Issue by ziweiji** [ttengwang/dense-video-captioning-pytorch#2]
If I have other videos (not from dataset), how to caption it?

**Comment by ttengwang** [comment]
Hi, the codes for feature extraction and proposal generation for customized datasets are not contained in this repo. You may prepare this data by yourself. 

Here are some tips:
1. follow [url](https://github.com/LuoweiZhou/anet2016-cuhk-feature) to extract frame-level features for each video 
2. generate a few event proposals for each videos, and replace `./data/generated_proposals/tsn_dbg_esgn_testset_num5044.json` with your json file.
   2.1  follow [url](https://github.com/Tencent/ActionDetection-DBG) to generate 100 proposals for each video. Other temporal action proposal models are also ok.
   2.2. follow [url](https://github.com/ttengwang/ESGN) to adopt ESGN to select a few proposals
