### ISSUE TITLE
Evalute Error 

### ISSUE THREAD

**Issue by SalocinB** [ttengwang/dense-video-captioning-pytorch#6]
Hi,
I tried to evaluate with this line from your README:
python eval.py --eval_folder $result_folder --eval_caption_file $val_caption_file --load_tap_json $lnt_tap_json, 
but I get an error from pycocoevalcap. 
The error I get is: 
score, scores = scorer.compute_score(gts[vid_id], res[vid_id])
  File "./densevid_eval3/coco-caption/pycocoevalcap/meteor/meteor.py", line 44, in compute_score
    score = float(self.meteor_p.stdout.readline().strip())
ValueError: could not convert string to float: 

I tried to debug using a print command. score contains:
[b'', b'', b'', b'', b'']

Have you ever seen this error?

Thank you in advance.

**Comment by ttengwang** [comment]
Hi, it’s  probably caused by the environmental setting. The code is tested on Ubuntu16.04 and Java1.8.0.  Do u use the same version?

**Comment by SalocinB** [comment]
Okay, thank you, I will try it. I use Java1.8.0_301 but Ubuntu 18.04.
