### ISSUE TITLE
How to use pre-trained model with .mp4 file?

### ISSUE THREAD

**Issue by preste-nakam** [ttengwang/dense-video-captioning-pytorch#8]
Hello!  Really great work!
Could you please help me? I'm trying to use your pre-trained model with my custom videos, but I don't understand how to use it with .mp4 video files.

Thanks in advance!

**Comment by ttengwang** [comment]
@preste-nakam Hi, please refer to #2.  I will consider simplifying the cumbersome pipeline and make it more friendly to real-word applications in the near future

**Comment by dawnlh** [comment]
> @preste-nakam Hi, please refer to #2. I will consider simplifying the cumbersome pipeline and make it more friendly to real-word applications in the near future

Looking forward to the improvement of the pipeline for custom video captioning~

**Comment by ttengwang** [comment]
Hi @dawnlh , we release another repo that supports processing mp4 videos at https://github.com/ttengwang/PDVC. I hope it's helpful for you.

**Comment by dawnlh** [comment]
Wonderful! I have tried it successfully! Thanks a lot~
